#!/bin/bash
#Proj9 Payroll step1

echo -e "###############
Enter info:
$> <enployee ID> <Fname> <Lname> <rate> <reg hrs> <OT hrs>
#################################"

if [ $# -ge 5 ];then
    emID=$1
    fname=$2
    lname=$3
    rate=$4
    reghr=$5
    othr=$6
fi

while [[ -z $othr ]] ;do
    echo "'$othr' was left blank so it was set to 0"
    othr=0
done
    ###### Calculate Pay ######
regpay=$(echo -e "scale=2;$rate*$reghr" | bc )
otpay=$(echo -e "scale=2;$rate*$othr*1.5 | bc )
total=$(echo -e "scale=2;$regpay+$otpay" | bc )

    ###### Output ######
echo -e "Employee ID: $emID   Name: $lname, $fname"
echo -e "Rate: \$$rate,  Regular pay: \$$regpay,  Overtime pay: \$$otpay,  Total: $total"
