#!/bin/bash 
 #Proj8 TaxRate 
 
 echo -e "\n######################################################### 
# TaxRate will add up upto 5 items and tell you the     # 
# price before and after tax, and the tax amount.       # 
# If you leave an item blank then it's considered \$0.00 # 
# Usage:                                                # 
#       Interactive mode.                               # 
#       Commandline parameters                          # 
# $> [taxrate] [item1] [item2] [item3] [item4] [item5]  # 
#########################################################" 
        ####### Reapeat? ###### 
count=1 # Setting count for repeat; If you used command line parameters this will ask you for new input
ans=true 
while [ $ans == true ] ;do 
        ###### Input ###### 
        #If you used command line parameters this will ask you for new input
        if [ $count -ge 2 ];then
                echo -e "\nEnter tax percentage: \c"
   		  read taxrate
		echo -e "Enter price for item 1: \c"
		  read item1
		echo -e "Enter price for item 2: \c"
		  read item2
		echo -e "Enter price for item 3: \c"
		  read item3
		echo -e "Enter price for item 4: \c"
		  read item4
		echo -e "Enter price for item 5: \c"
		  read item5
        elif [ $# -ge 2 ];then 
                taxrate=$1 
                item1=$2 
                item2=$3 
                item3=$4 
                item4=$5 
                item5=$6 
        else 
                 echo -e "\nEnter tax percentage: \c" 
                  read taxrate 
                echo -e "Enter price for item 1: \c" 
                  read item1 
                echo -e "Enter price for item 2: \c" 
                  read item2 
                echo -e "Enter price for item 3: \c" 
                  read item3 
                echo -e "Enter price for item 4: \c" 
                  read item4 
                echo -e "Enter price for item 5: \c" 
                  read item5 
        fi 
 
        ###### Data Validation ###### 
        while [[ $taxrate =~ [a-z] ]];do
                echo -e "'$taxrate' is not a number!"
                echo -e "Please enter a number for Tax: \c"
                  read taxrate
        done
        
#        echo -e "\nBefore tr: $taxrate" 
#        taxrate=$(echo "$taxrate" | tr -d [:alpha:] ) 
#        echo "After tr: $taxrate" 
 
         while  [[ $item1 =~ [a-z] ]] ;do
		echo -e "\n'$item1' is not a number!"
		echo -e "Please enter a number for item1: \c"
		read item1
	done

	while [[ $item2 =~ [a-z] ]];do
		echo -e "\n'$item2' is not a number!"
		echo -e "Please enter a number for item2: \c"
		read item2
	done

	while [[ $item3 =~ [a-z] ]];do
		echo -e "\n'$item3' is not a number!"
		echo -e "Please enter a number for item3: \c"
		read item3
	done

	while [[ $item4 =~ [a-z] ]];do
		echo -e "\n'$item4 is not a number!"
		echo -e "Please enter a number for item4: \c"
		read item4
	done

	while [[ $item5 =~ [a-z] ]];do
		echo -e "\n'$item5' is not a number!"
		echo -e "Please enter a number for item5: \c"
		read item5
	done
        
        if [-z $taxrate ];then
	        taxrate=0
	fi
	if [ -z $item1 ];then
		item1=0
	fi
	if [ -z $item2 ];then
		item2=0
	fi
	if [ -z $item3 ];then
		item3=0
	fi
	if [ -z $item4 ];then
		item4=0
	fi
	if [ -z $item5 ];then
		item5=0
	fi

        ###### Output ###### 
        echo -e "\nTax rate: $taxrate%" 
        echo -e "Price1: \$$item1" 
        echo -e "Price2: \$$item2" 
        echo -e "Price3: \$$item3" 
        echo -e "Price4: \$$item4" 
        echo -e "Price5: \$$item5" 
 
        ###### Calculation ###### 
        subtotal=$(echo "scale=2;$item1+$item2+$item3+$item4+$item5*1.00" | bc ) 
#       tax=$(echo "scale=4;$taxrate/100" | bc ) 
        echo "Tax: $taxrate%" # debug
        tax2=$(echo "scale=2;$subtotal*$taxrate/100" | bc ) 
        echo -e "Tax2: $tax2" 
        total=$(echo "$subtotal+$tax2" | bc ) 
 
        ###### Output ###### 
        echo -e "\nSubtotal: \$$subtotal" 
        echo -e "Tax:\$$tax2" 
        echo -e "Total: \$$total" 
 
        ###### Repeat? ###### 
        ans2=true 
        while [ $ans2 == true ]; do 
                echo -e " Would you like to repeat [y/n]? \c" 
                read repeat 
                case $repeat 
                        in 
                        y)ans2=false; ans=true;count$(echo "$count+1" | bc );; 
                        n)ans2=false; ans=false;; 
                        *)ans2=true;; 
                esac 
        done 
done 
