#!/bin/sh
#MyInfo proj 4
echo -e "\t You are: $(whoami)"
echo -e "\t Hostname: $HOSTNAME"
echo -e "\t Current directory: $(pwd)"
echo -e "\t Date & Time: $(date)"
echo -e "\t Number of user on the system: $(who |cut -d' ' -f1| sort | uniq | wc -l)"
