#!/bin/bash

checkfile(){
        ##### Checks to see if file exist #####
while [[ ! -f $list ]] ;do
        echo -e "\nFile $list doesn't exit!\nPlease enter file with IP list: \c"
        read list
done
}

maybe(){
case $hostip
        in
        stop)break;;
        quit)exit;;
esac
}

list=$1

        ##### Pulling host file from host #####
if [ -z $list ] ;then

        while true
        do
                echo -e "\nEnter host IP address: \c"
                read hostip
                maybe

                scp -p root@$hostip:/etc/hosts ~/$hostip

        done
else
        while read hostip ;do
                scp -p root@$hostip:/etc/hosts ~/host-$hostip
        done < $list
fi
