#!/bin/bash -x

#Pushing file to hosts

checkfile(){
while [[ ! -e $list ]]; do
        echo -e "\nFile $list doesn't exitst"
        echo -e "Pleas enter the list of IP(txt file): \c"
                read list
done
}


if [ $# -eq 0 ]; then

echo -e " #####################################################
#                                                     #
# This script will push a selected file to hosts      #
#                                                     #
# Ussage:                                             #
# $> . <script> <File to copy> <a file with host ips> #
# or                                                  #
# $> . <scrip> #Use the interactive mode              #
#                                                     #
#######################################################"

        read -p "Press any key to continue"

        echo -e "\n(Absolute path please)\nEnter file  to copy: \c"
                read file
        #file=/etc/hosts      # This was for testing

        echo -e "\nPlease enter  list of IPs(txt file): \c"
                read list
                checkfile
        #list=test2          # This was for testing

else
        file=$1
        list=$2
        checkfile
fi


while read hostip
do
        ssh -n $hostip "mv /etc/hosts /etc/hosts_bu && echo "$HOSTNAME - Host file has been renamed" "
        scp -p $file root@$hostip:/etc/
        echo -e "$hostip has been completed." >> completed_host

done < $list
